apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kkpxq0cnr-python 
  janus-idp.io/tekton: kkpxq0cnr-python
  backstage.io/kubernetes-id: kkpxq0cnr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kkpxq0cnr-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml