apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kkpxq0cnr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kkpxq0cnr-python 
  name: kkpxq0cnr-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kkpxq0cnr-python 
